project:
  type: website

website:
  title: "Drew Echerd"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/decherd
      - icon: twitter
        href: https://twitter.com/drewecherd
format:
  html:
    theme: cosmo
    css: styles.css



